version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose v2
          command: |
            curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker compose version
      - run:
          name: Run tests
          command: |
            docker compose up -d
            docker compose run dockerapp python test.py
